# Project information
site_name: SQL Engine
site_description: SQL Engine
site_author: HyperJ
site_url: https://hyperj.github.io/docs.sql-engine/

# Repository
repo_name: hyperj/docs.sql-engine
repo_url: https://github.com/hyperj/docs.sql-engine
edit_uri: blob/master/docs/

# Copyright
copyright: Copyright &copy; 2009 - 2018 HyperJ

# Configuration
theme:
  name: material

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  feature:
    tabs: true
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/images/favicon.ico
  logo: assets/images/favicon.ico

# Customization
extra:
  social:
    - type: github-alt
      link: https://gist.github.com/hyperj/
    - type: github
      link: https://github.com/hyperj
    - type: h-square
      link: http://blog.hyperj.net
    - type: linkedin
      link: https://www.linkedin.com/in/hyperj
  pagetime: 'on'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Home: index.md
  - Retreat: retreat.md
  - Relational Model: relational-model.md
  - Relational Algebra: relational-algebra.md
  - Base:
    - Network: network.md
    - Scheduler: scheduler.md
    - Storage: storage.md
    - Compute: compute.md
    - Metrics: metrics.md
  - SQL:
    - Catalyst: catalyst.md
    - Case: case.md
    - Tuning: tuning.md
  - Practices:
    - Work & Practices: work-and-practices.md
    - Projects & Articles: projects-and-articles.md
  - Appendix:
    - Appendix A: appendix-a.md
    - Appendix B: appendix-b.md

# Analytics


